main: BreedingBuddies.BreedingBuddies
api-version: 1.20
name: BreedingBuddies
version: 1.0
author: Nowko
depend: [MMOItems, MythicLib]
commands:
  breedingbuddies:
    description: Main command for BreedingBuddies plugi
    usage: /<command> <subcommand>
    permission: breedingbuddies.use
    permission-message: You do not have permission to use this command.